package com.sma.sma_coding_dev_flutter_sdk

import com.szabh.smable3.component.PowerSaveModeState

object SdkMethod {
    // BleScanner methods
    const val build = "build"
    const val scan = "scan"
    const val exit = "exit"

    // BleScanCallback method
    const val onBluetoothDisabled = "onBluetoothDisabled"
    const val onScan = "onScan"
    const val onDeviceFound = "onDeviceFound"

    // BleConnector methods
    const val init = "init"
    const val sendData = "sendData"
    const val sendBoolean = "sendBoolean"
    const val sendInt8 = "sendInt8"
    const val sendInt16 = "sendInt16"
    const val sendInt32 = "sendInt32"
    const val sendObject = "sendObject"
    const val sendStream = "sendStream"
    const val connectClassic = "connectClassic"
    const val launch = "launch"
    const val unbind = "unbind"
    const val isBound = "isBound"
    const val isAvailable = "isAvailable"
    const val setAddress = "setAddress"
    const val connect = "connect"
    const val closeConnection = "closeConnection"
    const val startOTA = "startOTA"
    const val releaseOTA = "releaseOTA"
    const val startMusicController = "startMusicController"
    const val stopMusicController = "stopMusicController"
    const val saveLogs = "saveLogs"
    const val setPhoneStateListener = "setPhoneStateListener"
    const val setDataKeyAutoDelete = "setDataKeyAutoDelete"
    const val isConnecting = "isConnecting"
    const val isMusicControllerRunning = "isMusicControllerRunning"
    const val sendMusicPlayState = "sendMusicPlayState"
    const val sendMusicTitle = "sendMusicTitle"
    const val sendPhoneVolume = "sendPhoneVolume"

    // BleHandleCallback methods
    const val onDeviceConnected = "onDeviceConnected"
    const val onIdentityCreate = "onIdentityCreate"
    const val onIdentityDelete = "onIdentityDelete"
    const val onIdentityDeleteByDevice = "onIdentityDeleteByDevice"
    const val onSessionStateChange = "onSessionStateChange"
    const val onCommandReply = "onCommandReply"
    const val onReadPower = "onReadPower"
    const val onReadFirmwareVersion = "onReadFirmwareVersion"
    const val onReadSedentariness = "onReadSedentariness"
    const val onReadNoDisturb = "onReadNoDisturb"
    const val onNoDisturbUpdate = "onNoDisturbUpdate"
    const val onReadAlarm = "onReadAlarm"
    const val onAlarmUpdate = "onAlarmUpdate"
    const val onAlarmDelete = "onAlarmDelete"
    const val onAlarmAdd = "onAlarmAdd"
    const val onFindPhone = "onFindPhone"
    const val onReadUiPackVersion = "onReadUiPackVersion"
    const val onReadLanguagePackVersion = "onReadLanguagePackVersion"
    const val onSyncData = "onSyncData"
    const val onReadActivity = "onReadActivity"
    const val onReadHeartRate = "onReadHeartRate"
    const val onUpdateHeartRate = "onUpdateHeartRate"
    const val onReadBloodPressure = "onReadBloodPressure"
    const val onReadSleep = "onReadSleep"
    const val onReadWorkout = "onReadWorkout"
    const val onReadLocation = "onReadLocation"
    const val onReadTemperature = "onReadTemperature"
    const val onReadBloodOxygen = "onReadBloodOxygen"
    const val onReadBleHrv = "onReadBleHrv"
    const val onCameraStateChange = "onCameraStateChange"
    const val onCameraResponse = "onCameraResponse"
    const val onStreamProgress = "onStreamProgress"
    const val onRequestLocation = "onRequestLocation"
    const val onDeviceRequestAGpsFile = "onDeviceRequestAGpsFile"
    const val onIncomingCallStatus = "onIncomingCallStatus"
    const val onReadPressure = "onReadPressure"
    const val onFollowSystemLanguage = "onFollowSystemLanguage"
    const val onReadWeatherRealTime = "onReadWeatherRealTime"
    const val onReadWorkout2 = "onReadWorkout2"
    const val onCommandSendTimeout = "onCommandSendTimeout"
    const val onOTAProgress = "onOTAProgress"
    const val onReadDeviceInfo = "onReadDeviceInfo"
    const val onReadBleAddress = "onReadBleAddress"
    const val onReceiveMusicCommand = "onReceiveMusicCommand"
    const val onReadTemperatureUnit = "onReadTemperatureUnit"
    const val onReadDateFormat = "onReadDateFormat"
    const val onVibrationUpdate = "onVibrationUpdate"
    const val onBacklightUpdate = "onBacklightUpdate"
    const val onReadGestureWake = "onReadGestureWake"
    const val onGestureWakeUpdate = "onGestureWakeUpdate"
    const val onPowerSaveModeState = "onPowerSaveModeState"
    const val onPowerSaveModeStateChange = "onPowerSaveModeStateChange"
    const val onReadLoveTapUser = "onReadLoveTapUser"
    const val onLoveTapUserUpdate = "onLoveTapUserUpdate"
    const val onLoveTapUserDelete = "onLoveTapUserDelete"
    const val onReadMedicationReminder = "onReadMedicationReminder"
    const val onMedicationReminderUpdate = "onMedicationReminderUpdate"
    const val onMedicationReminderDelete = "onMedicationReminderDelete"
    const val onLoveTapUpdate = "onLoveTapUpdate"
    const val onReadUnit = "onReadUnit"
    const val onReadDeviceInfo2 = "onReadDeviceInfo2"
    const val onReadHrMonitoringSettings = "onReadHrMonitoringSettings"
    const val onDeviceConnecting = "onDeviceConnecting"
    const val onReadBacklight = "onReadBacklight"
    const val onReadHourSystem = "onReadHourSystem"
}